export const gameConstants = {
	BUTTON_DEFAULT_COLOR: "#ffffff",
	BUTTON_HOVER_COLOR: "#bd3500",
	CHALLENGE_WORD_SIZE: 10,
	CHAR_Z: 50,
	INITIAL_SPAWN_RATE: 30,
	SCOREBOARD_TEXT_SIZE: 50,
	SPRITE_SCALE: 2,
	TEXT_Z: 51,
	TEXT_SHADOW_Z: 50,
};
