/*
 * ALL WORDS/PHRASES MUST BE ADDED LOWERCASE
 */

export const wordBank: string[] = [
	// Agori
	"atakus",
	"berix",
	"crotesius",
	"kirbold",
	"kirbraz",
	"kyry",
	"lein",
	"metus",
	"raanu",
	"sahmad",
	"scodonius",
	"tarduk",
	"zesk",

	// Barraki
	"carapar",
	"ehlek",
	"kalmah",
	"mantax",
	"pridak",
	"takadox",

	// Bohrok
	"cahdok",
	"gahdok",
	"gahlok",
	"kohrok",
	"lehvak",
	"nuhvok",
	"pahrak",
	"tahnok",
	"gahlok kal",
	"kohrok kal",
	"lehvak kal",
	"nuhvok kal",
	"pahrak kal",
	"tahnok kal",
	"gahlok va",
	"kohrok va",
	"lehvak va",
	"nuhvok va",
	"pahrak va",
	"tahnok va",

	// Comics
	/* "pak man",
    "steak boy",
    "the chilli god",
    "tirvon", */

	// Concepts
	"akalini",
	"chute speak",
	"destiny",
	"duty",
	"kolhii",
	"red star",
	"the three virtues",
	"tree speak",
	"unity",

	// Dark Hunters
	"airwatcher",
	"amphibax",
	"charger",
	"conjurer",
	"darkness",
	"devastator",
	"dweller",
	"eliminator",
	"firedracax",
	"gatherer",
	"gladiator",
	"guardian",
	"kraata-kal",
	"krekka",
	"lariska",
	"lurker",
	"mimic",
	"minion",
	"nidhiki",
	"phantom",
	"poison",
	"primal",
	"prototype",
	"ravager",
	"savage",
	"seeker",
	"sentrakh",
	"shadow stealer",
	"silence",
	"spinner",
	"subterranean",
	"the recorder",
	"tracker",
	"triglax",
	"tyrant",
	"vanisher",
	"vengeance",
	"voporak",
	"the shadowed one",

	// Elements
	"air",
	"earth",
	"fire",
	"gravity",
	"ice",
	"iron",
	"light",
	"lightning",
	"magnetism",
	"plasma",
	"psionics",
	"sand",
	"shadow",
	"sonics",
	"stone",
	"the green",
	"water",

	// Events
	"great cataclysm",
	"matoran civil war",
	"siege of metru nui",

	// Fandom/Community/Culture
	"all american rejects",
	"all insane kids",
	"an cool dude",
	"ask gregf",
	"avak roxorz my soxorz",
	"battle for power",
	"brakelatabasaasta feed me :wacko:",
	"burn stuff",
	"bye bye babylon",
	"cathy hapka",
	"caught up in a dream",
	"closer to the truth",
	"crashed",
	"creeping in my soul",
	"creeps in the deep",
	"cryoshell",
	"daughtry",
	"defeater of doors",
	"face me",
	"free the band",
	"gravity hurts",
	"greg farshtey",
	"hail denmark",
	"hero",
	"hoseryx",
	"inika island assault",
	"it's not a moustache",
	"kanohi, apply directly to the forehead",
	"lime green joint",
	"mantax facts",
	"mata nui online game",
	"matoran escape",
	"move along",
	"ohez noez it is teh zamorzorz",
	"picture of a garbage can",
	"piraka attack",
	"piraka rap",
	"platinum hau",
	"scottish-accent pills",
	"secret stomache message",
	"silly songs with kopaka",
	"the miru is a dumb mask",
	"toa of plasma screen televisions",
	"you can't peel a car",
	"yo yo piraka",

	// Glatorian
	"ackar",
	"certavus",
	"gelu",
	"gresh",
	"kiina",
	"malum",
	"perditus",
	"strakk",
	"tarix",
	"vastus",
	"skrall",
	"branar",
	"stronius",
	"tuma",
	"vorox",
	"kabrua",

	// Great Beings
	"angonce",
	"heremus",

	// Kanohi
	"akaku",
	"aki",
	"arthron",
	"avsa",
	"calix",
	"copper mask of victory",
	"crast",
	"elda",
	"faxon",
	"felnas",
	"garai",
	"hau",
	"huna",
	"iden",
	"ignika",
	"jutlin",
	"kadin",
	"kakama",
	"kaukau",
	"komau",
	"kualsi",
	"mahiki",
	"matatu",
	"miru",
	"mohtrek",
	"olisi",
	"olmak",
	"pakari",
	"pehuki",
	"rau",
	"rode",
	"rua",
	"ruru",
	"sanok",
	"shelek",
	"suletu",
	"tryna",
	"vahi",
	"volitak",
	"zatth",

	// Kanoka Powers
	"reconstitute at random",
	"freeze",
	"weaken",
	"remove poison",
	"enlarge",
	"shrink",
	"regenerate",
	"teleport",

	// Locations
	"amaja-nui",
	"aqua magna",
	"atero",
	"bara magna",
	"black spike mountains",
	"black water",
	"bota magna",
	"cavern of historical records",
	"cavern of light",
	"chamber of truth",
	"charred jungle",
	"coliseum",
	"creep canyon",
	"dark falls",
	"dunes of treason",
	"east garden",
	"elbow peak",
	"fau swamp",
	"field of mist",
	"fields of air",
	"forest of blades",
	"gate of ice",
	"gatherer's ridge",
	"ga-kini",
	"ga-koro",
	"ga-suva",
	"ga-wahi",
	"great mine",
	"great volcano",
	"hura-mafa river",
	"iconox",
	"iron canyon",
	"kanae bay",
	"knee island",
	"ko-kini",
	"ko-koro",
	"ko-suva",
	"ko-wahi",
	"kraata cave",
	"krana pit",
	"kumu islets",
	"lake kanae",
	"lake of fire",
	"lake pala",
	"lein's drift",
	"leva bay",
	"le-kini",
	"le-koro",
	"le-suva",
	"le-wahi",
	"lost reef",
	"mangai volcano",
	"marn tunnels",
	"mata nui",
	"matoran cliff village",
	"mahri nui",
	"metru nui",
	"motara desert",
	"mount ihu",
	"naho bay",
	"naho falls",
	"north march",
	"nui-rama hive",
	"northern continent",
	"northern frost",
	"octo cave",
	"old fusa path",
	"onu-kini",
	"onu-koro",
	"onu-suva",
	"onu-wahi",
	"papa nihu reef",
	"path of prophecies",
	"pillars of salt",
	"piraka stronghold",
	"place of shadow",
	"po-kini",
	"po-koro",
	"po-koro quarry",
	"po-suva",
	"po-wahi",
	"razor whale's teeth",
	"river dormus",
	"roxtus",
	"sacred fire",
	"sanctum",
	"sandray canyon",
	"sea of liquid sand",
	// "secret cave",
	"skakdi fortress",
	"skrall river",
	"skull mountain",
	"solis magna",
	"southern continent",
	"spherus magna",
	"spirit's wish",
	"sundial entrance",
	"suva-kaita",
	"tajun",
	"ta-kini",
	"ta-koro",
	"ta-suva",
	"ta-wahi",
	"tesara",
	"the cord",
	"the drifts",
	"three brothers bridge",
	"tiro canyon",
	"tren krom break",
	"valley of the maze",
	"voya nui",
	"vulcanus",
	"wall of history",
	"wall of prophecy",
	"wall of stars",
	// "wastelands",
	"white quartz mountains",
	"zakaz",

	// Makuta
	"antroz",
	"bitil",
	"chirox",
	"gorast",
	"icarax",
	"kojol",
	"krika",
	"miserix",
	"mutran",
	"spiriah",
	"teridax",
	"tridax",
	"vamprah",

	// Order of Mata Nui
	"ancient",
	"axxon",
	"botar",
	"brutaka",
	"helryx",
	"hydraxon",
	"jerbraz",
	"johmak",
	"krakua",
	"mazeka",
	"tobduk",
	"trinuma",

	// Races
	"agori",
	"bahrag",
	"barraki",
	"bohrok",
	"glatorian",
	"makuta",
	"matoran",
	"rahi",
	"toa",
	"turaga",
	"vahki",
	"vortixx",

	// Rahi
	"acidfly",
	"air serpent",
	"archives beast",
	"archives mole",
	"artakha bull",
	"ash bear",
	"avohkah",
	"blade burrower",
	"bog leech",
	"bog snake",
	"borer worm",
	"brakas",
	"burnak",
	"cable crawler",
	"catapult scorpion",
	"cave fish",
	"chute lurker",
	"cliff bug",
	"cliff screecher",
	"colony drone",
	"crystal climber",
	"crystal serpent",
	"dagger spider",
	"dermis turtle",
	"devourer",
	"dikapi",
	"doom viper",
	"dust darter",
	"dweller in the deep",
	"electric bug",
	"electric spider",
	"energy hound",
	"fader bull",
	"feeder worm",
	"fenrakk spawn",
	"fikou",
	"fikou-nui",
	"fire entity",
	"fireflyer",
	"fire serpent",
	"first rahi",
	"frost beetle",
	"frost leech",
	"furnace salamander",
	"fusa",
	"gadunka",
	"gafna",
	"gate guardian",
	"ghekula",
	"giant shark",
	"giant squid",
	"giant swamp lizard",
	"great temple squid",
	"gukko",
	"hahnah",
	"hapaka",
	"hikaki",
	"hoto",
	"husi",
	"hydruka",
	"ice bat",
	"ice vermin",
	"infernavika",
	"kahu",
	"kane-ra",
	"kanohi dragon",
	"kavinika",
	"keras",
	"kewa",
	"kikanalo",
	"kinloka",
	"kirikori nui",
	"klakk",
	"kofo-jaga",
	"kraawa",
	"krahka",
	"kratana",
	"kuma-nui",
	"lava ape",
	"lava crawler",
	"lava eel",
	"lava hawk",
	"lava rat",
	"lightfish",
	"lohrak",
	"longfang",
	"mahi",
	"makika",
	"makuta fish",
	"mana ko",
	"manas",
	"manutri",
	"mata nui cow",
	"mata nui fishing bird",
	"metallic hornet",
	"metru mantis",
	"moa",
	"muaka",
	"mud crawler",
	"mukau",
	"necrofinch",
	"niazesk",
	"night creeper",
	"nivawk",
	"nui-jaga",
	"nui-kopen",
	"nui-rama",
	"parakrekks",
	"phase dragon",
	"pit war tortoise",
	"pokawi",
	"proto drake",
	"protodax",
	"protodite",
	"rahi nui",
	"rahi-matoran hybrid",
	"ranama",
	"razorcrab",
	"razorfish",
	"razor whale",
	"red serpent",
	"reef raider",
	"rock lion",
	"rock raptor",
	"rock ussal",
	"rock worm",
	"ruki",
	"sand frog",
	"sand screamer",
	"sand snipe",
	"sand tarakava",
	"sea spider",
	"shallows cat",
	"shore turtle",
	"silver chute spider",
	"slime-worm",
	"smoke hawk",
	"spider crab",
	"spiked fire worm",
	"spiny stone ape",
	"spine slug",
	"stinger whale",
	"stone rat",
	"stone snake",
	"swamp stalker",
	"subterranean worm",
	"tahtorak",
	"takea",
	"taku",
	"tarakava",
	"tarakava nui",
	"the mountain",
	"toa terrain crawler",
	"troller",
	"tunnel stalker",
	"tunneler",
	"two-headed tarakava",
	"ussal crab",
	"vahki hunter",
	"vako",
	"venom flyer",
	"venom eel",
	"visorak",
	"waikiru",
	"water wraith",
	"zivon",

	// Rahi, named
	"fenrakk",
	"graalok",
	"ka",
	"kardas",
	"morak",
	"pewku",
	"thulox",
	"spinax",

	// Skakdi
	"avak",
	"hakann",
	"nektann",
	"reidak",
	"thok",
	"vezok",
	"vezon",
	"zaktan",

	// Titans
	"artakha",
	"exo-toa",
	"golden being",
	"karzahni",
	"maxilos",
	"morbuzakh",
	"nocturn",
	"roodaka",
	"sidorak",
	"keetongu",
	"takutanuva",
	"tren krom",
	"umbra",

	// Toa Hagah
	"bomonga",
	"gaaki",
	"iruni",
	"kualus",
	"norik",
	"pouks",

	// Toa Inika
	"hahli",
	"hewkii",
	"jaller",
	"kongu",
	"matoro",
	"nuparu",

	// Toa Mata
	"gali",
	"lewa",
	"kopaka",
	"onua",
	"pohatu",
	"tahu",

	// Toa Metru
	"matau",
	"nokama",
	"nuju",
	"onewa",
	"vakama",
	"whenua",

	// Toa, Other
	"chiara",
	"dume",
	"jovan",
	"lesovikk",
	"lhikan",
	"naho",
	"nikila",
	"orde",
	"takanuva",
	"tuyet",
	"varian",
	"zaria",

	// TTV Members
	"avohkah tamer",
	"eljay",
	"exxtrooper",
	"gundam lady",
	"leo",
	"mesonak",
	"prpldragon",
	"starbreaker",
	"takuma nuva",
	"tenebrae invictus",
	"varderan",
	"venom",
	"phweffie",
	"xeros",

	// Vahki
	"bordakh",
	"keerakh",
	"kraahu",
	"kralhi",
	"kranua",
	"nuurakh",
	"rorzakh",
	"vorzakh",
	"zadakh",

	// Vision Powers
	"heat vision",
	"impact vision",
	"infrared vision",
	"laser vision",
	"spellbinder vision",
	"telescopic vision",
	"x-ray vision",

	// Visorak
	"boggarak",
	"kahgarak",
	"keelerak",
	"oohnorak",
	"roporak",
	"suukorak",
	"vohtarak",

	// Weapons & Tools
	"catcher claws",
	"claw arm",
	"cordak blaster",
	"eccentric boulder",
	"electro-rocket",
	"energy siphon blade",
	"heart of the visorak",
	"herding blade",
	"hook blades",
	"kanohi",
	"kanoka disk launcher",
	"matoran sphere",
	"rotating shadow sword",
	"shadow blade",
	"shadow spear",
	"staff of darkness",
	"tridax pod",
	"bohrok shields",
	"stun staff",
	"buzz saw",
	"crescent scythe",
	"devastator",
	"harpoon",
	"ice gun",
	"lava launcher",
	"lava surfboard",
	"protosteel tri-talons",
	"seismic pickaxe",
	"spear of fusion",
	"three-bladed scissor",
	"explosive boomerang",
	"sonic vibration sword",
	"twin-bladed black fire sword",
	"adaptive armor",
	"air katana",
	"air saber",
	"aqua axes",
	"lewa's axe",
	"blizzard blade",
	"onua's claws",
	"feet additions",
	"fire sword",
	"hooks",
	"ice blade",
	"kopaka's ice shield",
	"ice sword",
	"magma swords",
	"multi-resistant shield",
	"power lance",
	"rotating fire blades",
	"staff of light",
	"twin light staffs",
	"twin propellers",
	"aero slicers",
	"badge of office",
	"blazer claws",
	"claw clubs",
	"crystal spikes",
	"drill of onua",
	"earthshock drills",
	"fang blades",
	"fin barbs",
	"firestaff",
	"hordika teeth",
	"hydroblades",
	"ice pick",
	"kau kau staff",
	"rhotuka launcher",
	"proto pitons",
	"stone hammer",
	"thumpers",
	"trident of nokama",
	"avalanche spear",
	"cyclone spear",
	"fire greatswords",
	"lava spear",
	"scythe",
	"seismic spear",
	"sub-zero spear",
	"tidal spear",
	"aqua blaster blade",
	"aqua warblade",
	"aquatic power blade",
	"climbing chain",
	"electrified chains",
	"energized flame sword",
	"energized ice sword",
	"giant claws",
	"laser axe",
	"laser crossbow",
	"laser drill",
	"laser harpoon",
	"protosteel talons",
	"razor-edged protosteel shield",
	"twin cutter",
	"magnetic bolt launcher",
];
